carbon-design-system/carbon-addons-cloud-react

package.json
src/index.js

Adds in ResourceHeader export and updates peer dependency versions

 fix(package): add ResourceHeader export

---

src/index.js

Updates export to read from `default`.

fix(resource-header): add proper export

---

package.json

Should help with bundling issues for some consumers.
**New**
- Add `sideEffects` flag to `package.json`

fix: add 'sideEffects' flag

---

package.json

bumping version of react components for dev

fix(filters): up dependency of react components

---

src/components/MultiSelect/index.js

**Changed**
- NesteFilterableMultiSelect is being exported instead of FilterableMultiselect

fix(filters): export the nested filterbale multiselect

---

src/index.js

Nested Component exported from the right file : export NestedFilterableMultiSelect from './components/MultiSelect';

fix(filters): nested component exported

---

src/components/Checkbox/CheckBoxIcon.js
src/components/Checkbox/Checkbox.js
src/components/ListBox/ListBoxMenuIcon.js
src/components/ListBox/ListBoxSelection.js
src/components/MultiSelect/MultiSelect-story.js
src/components/MultiSelect/NestedFilterableMultiselect.js
src/components/MultiSelect/tools/filter.js
src/components/MultiSelect/tools/groupedByCategory.js
src/components/MultiSelect/tools/sorting.js

This adds logic as
- Default sort function by category
- Checkbox parent showed as partial when not all its childs are checked.
- Preselect items logic

Filterablefixes

---

package.json
src/components/MultiSelect/__tests__/NestedFilterableMultiselect-test.js
src/components/MultiSelect/__tests__/__snapshots__/NestedFilterableMultiselect-test.js.snap

Add unit test cases to NestedFilterableMultiselect component

fix(filters): add test cases for the NestedFilterableMultiselect

---

package.json
src/components/Checkbox/Checkbox-test.js
src/components/Checkbox/Checkbox.js
src/components/MultiSelect/NestedFilterableMultiselect.js
src/components/Tooltip/MouseOverTooltip-test.js
src/components/Tooltip/MouseOverTooltip.js
src/components/Tooltip/index.js

Add tooltip support in checkbox entries in NestedFilterableMultiSelect component

fix(filters): support tooltip in checkbox

---

src/components/Checkbox/Checkbox-test.js
src/components/Checkbox/Checkbox.js
src/components/MultiSelect/NestedFilterableMultiselect.js
src/components/MultiSelect/__tests__/__snapshots__/NestedFilterableMultiselect-test.js.snap

Fix accessibility found in NestedFilterableMultiSelect component

fix(filters): fix accessibility

---

src/components/MultiSelect/__tests__/NestedFilterableMultiselect-test.js

Added some testCases for the multi select component.

fix(filters): test cases multi select

---

package.json
src/components/Checkbox/Checkbox-test.js
src/components/Checkbox/Checkbox.js
src/components/Tooltip/MouseOverTooltip-story.js
src/components/Tooltip/MouseOverTooltip-test.js
src/components/Tooltip/MouseOverTooltip.js
src/index.js

Exposing the new tooltip component for other components to consume.

feat(tooltip): expose the new tooltip component 

---

src/components/Tooltip/MouseOverTooltip-test.js
src/components/Tooltip/MouseOverTooltip.js

Removing hacking code as the original issue is now fixed: https://github.com/IBM/carbon-components-react/issues/1617

fix(tooltip): remove hack code to override tooltip tabIndex

---

src/components/DetailPageHeader/DetailPageHeader-story.js

**Changed**
- DPH story to fix module reference, etc.

chore(detail-page-header): fix Storybook

---

src/components/TagList/TagList-story.js
src/components/TagList/TagList-test.js
src/components/TagList/TagList.js

fix(tags): a11y, editable on hover

---

src/components/TagList/TagList.js

fix(tags): show edit button on focus

---

.storybook/addons.js
package.json
src/components/MultiSelect/MultiSelect-story.js
src/components/MultiSelect/NestedFilterableMultiselect.js
src/components/MultiSelect/__tests__/NestedFilterableMultiselect-test.js
src/components/MultiSelect/__tests__/__snapshots__/NestedFilterableMultiselect-test.js.snap
src/components/MultiSelect/tools/__tests__/sorting-test.js
src/components/MultiSelect/tools/filter.js
src/components/MultiSelect/tools/sorting.js
src/internal/Selection.js

The current implementation supports only 2 level. Rewriting the component to support 2 or more hierarchical level.

Support multi-level hierarchy in FilterableMultiselect component

---

src/components/TagList/TagList.js

**Changed**
- Exposes `iconTitle` and `iconDescription` as props to allow for i18n

fix(tag-list): adds icon title and description props for i18n

---

src/components/InteriorLeftNavList/InteriorLeftNavList-test.js
src/components/InteriorLeftNavList/InteriorLeftNavList.js

To support rendering custom node for the title element.

fix(interiorleftnav): support custom title node

---

package.json
src/components/MultiSelect/NestedFilterableMultiselect.js

- Fix accessibility
- Fix https://github.com/carbon-design-system/carbon-addons-cloud-react/issues/98

fix(filters): fix accessibility and issue 98
